sudo: required

language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

compiler:
  - gcc

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc-4
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - nvidia-cuda-dev
          - libcuda1-384
          - build-essential
          - gcc-4-multilib
          - gcc-4
          - g++-4
          - cmake
          - doxygen
    env:
      - MATRIX_EVAL="gcc-4 && CXX=g++-4 && NPROC=$(nproc)"

# Before compile
install:
  - ./build_files/build_environment/install_deps.sh --skip-osl --no-confirm

script:
  - mkdir build
  - cd build
  - cmake .. && make
